### ISSUE TITLE
inside GatsbyJS

### ISSUE THREAD

**Issue by NickyMeuleman** [prismagraphql/vscode-graphql#51] opened 2018-07-09 14:49 UTC
Hi!
I'm trying to get this VSCode extension working for a [Gatsby](https://www.gatsbyjs.org/) site.
I have the results of the introspectionquery stored in `schema.json` in the root of the project.
Also in the root of the project is a `.graphqlconfig.yml` that only contains `schemaPath: schema.json`

Gatsby uses tagged strings for graphQL, but the tag is `graphql`, not `gql` like in Apollo.
Syntax highlighting does work.

How should I further configure things to also get the autocomplete suggestions/query validation from this plugin?

To reproduce:

- Clone a Gatsby project that uses Graphql. (I tried this on [my blog](https://github.com/NickyMeuleman/nicky-blog))
- Add [gatsby-plugin-extract-schema](https://next.gatsbyjs.org/packages/gatsby-plugin-extract-schema/) to get the `schema.json` file.
- Create a `.graphqlconfig.yml` file

Thanks!

edit: Oops, part duplicate of #49.

**Comment by divyenduz** [comment] 2018-07-13 14:12
Closing as duplicate of https://github.com/prismagraphql/vscode-graphql/issues/49

**Comment by divyenduz** [comment] 2018-07-13 14:33
Closing as duplicate of #49

**Closed by divyenduz** 2018-07-13 14:33 UTC
